[package]
name = "esp-idf-hal"
version = "0.2.0"
authors = ["sapir <yasapir@gmail.com>"]
edition = "2018"
description = "an embedded-hal implementation for Rust on ESP32 with esp-idf"
repository = "https://github.com/sapir/esp-idf-hal"
license = "MIT"

[dependencies]
embedded-hal = { version = "0.2.3", features = ["unproven"] }
esp-idf-sys = "0.1.2"
nb = "0.1.2"
genio = { version = "0.2.0", default-features = false }

# no xtensa in regular compiler yet
[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[features]
default = ["install_panic_handler"]
alloc = []
install_panic_handler = []
